{
    "name":'hotel_management_system',
    "version" :"18.0.1.0",
    "summary":"hotel management system",
    # 'category': 'Hotel Management/user',
    'sequence': 1,
    'depends': ['base','sale','contacts','account'],
    "data" :[
        "security/ir.model.access.csv",
        "data/data.xml",
        "data/mail_template.xml",
        "view/hotel_hotel_view.xml",
        "view/hotel_rooms_view.xml",
        "view/hotel_policy_view.xml",
        "view/hotel_room_price_view.xml",
        "view/hotel_room_type_view.xml",
        "view/hotel_season_view.xml",
        "view/hotel_services_view.xml",
        # "view/hotel_room_image_view.xml",
        "view/hotel_aminities_view.xml",
        "view/hotel_room_availability.xml",
        "view/hotel_room_reservation.xml",
        "view/hotel_guest_view.xml",
        "view/hotel_room_specification.xml",
        "view/hotel_view_config.xml",
        "view/hotel_pricelist_view.xml",
        "view/hotel_housekeeping_staff.xml",
        "view/housekeeping_maintainance_type.xml",
        "view/housekeeping_staff_attendence.xml",
        "view/housekeeping_planning_view.xml",
        "view/housekeeping_report_issue_view.xml",
        "view/housekeeping_report_issue.xml",
        "view/hotel_restaurant_view.xml",
        "view/hotel_restaurant_user_view.xml",
        "view/hotel_food_item_view.xml",
        "view/housekeeping_check_list.xml",
        "view/housekeeping_maintainance_service.xml",
        "view/menu.xml",
        "wizard/show_available_room.xml"
    ],
    "license": 'LGPL-3',
    "installable" : True,
    "application" : True,
}

